package com.futurebank.accountService.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

@Data // Generates getters, setters, toString, equals, and hashCode methods
@NoArgsConstructor // Generates the no-arg constructor
@AllArgsConstructor // Generates the all-args constructor
public class TransferRequest {

    @NotNull(message = "From account ID cannot be null")
    private Long fromAccount;

    @NotNull(message = "To account ID cannot be null")
    private Long toAccount;

    @NotNull(message = "Amount cannot be null")
    @Min(value = 0, message = "Amount must be greater than 0")
    private Double amount;

    @NotNull(message = "Category cannot be null")
    private String category; // Renamed to follow Java naming conventions

    // No need to manually declare constructors or getter/setter methods as Lombok annotations take care of them.

    // The toString method is also generated by the @Data annotation.
}
